import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { Avatar, MoviePoster, Pill, PrimaryButton, SectionTitle } from '@/components/CineGoUI';
import { movies } from '@/data/movies';
import { useColors } from '@/hooks/useColors';
import { useCineGo } from '@/context/CineGoContext';
export default function MovieDetail() {
 const { id } = useLocalSearchParams<{ id: string }>(); const movie = movies.find(item => item.id === id) ?? movies[0]; const colors = useColors(); const insets = useSafeAreaInsets(); const { interested, toggleInterest, addPlan } = useCineGo();
 const selectTime = (time: string) => toggleInterest(`${movie.id}-${time}`);
 return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.container, { paddingBottom: insets.bottom + 30 }]}><View style={styles.hero}><MoviePoster source={movie.poster} /><View style={styles.heroInfo}><Pill active>{movie.genre.split(' · ')[0]}</Pill><Text style={[styles.title, { color: colors.foreground }]}>{movie.title}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{movie.runtime}  ·  {movie.rating}/10</Text><View style={styles.cinema}><Feather name="map-pin" size={14} color={colors.primary} /><Text style={[styles.meta, { color: colors.mutedForeground }]}>{movie.cinema} · {movie.area}</Text></View></View></View><Text style={[styles.description, { color: colors.mutedForeground }]}>{movie.description}</Text><SectionTitle title="Choose a showtime" /><View style={styles.times}>{movie.times.map(time => { const active = interested.includes(`${movie.id}-${time}`); return <Pressable key={time} onPress={() => selectTime(time)} style={[styles.time, { backgroundColor: active ? colors.primary : colors.secondary }]}><Text style={[styles.timeText, { color: active ? colors.primaryForeground : colors.foreground }]}>{time}</Text>{active && <Feather name="check" size={14} color={colors.primaryForeground} />}</Pressable> })}</View><View style={styles.interestNote}><Feather name="info" size={15} color={colors.accent} /><Text style={[styles.note, { color: colors.mutedForeground }]}>Registering interest lets nearby cinephiles know you’re considering this screening. No ticket is purchased.</Text></View><SectionTitle title={`${movie.attendees.length + 1} people are interested`} action="Near you" /><View style={styles.attendees}>{movie.attendees.map(person => <View key={person.name} style={[styles.person, { borderBottomColor: colors.border }]}><Avatar name={person.name} color={colors.accent} /><View style={{ flex: 1 }}><Text style={[styles.personName, { color: colors.foreground }]}>{person.name} <Text style={[styles.age, { color: colors.mutedForeground }]}>| {person.age}</Text></Text><Text style={[styles.personMeta, { color: colors.mutedForeground }]}>{person.distance} · {person.minutes}</Text></View><PrimaryButton label="Make plan" compact icon="message-circle" onPress={() => { addPlan({ id: `${movie.id}-${person.name}`, movieId: movie.id, person: person.name, time: movie.times[1], cinema: movie.cinema, status: 'Pending' }); router.push(`/chat/${movie.id}-${person.name}`); }} /></View>)}</View><View style={[styles.safe, { backgroundColor: colors.secondary }]}><Feather name="shield" size={16} color={colors.primary} /><Text style={[styles.safeText, { color: colors.mutedForeground }]}>Stay safe: meet in public, keep chats in CineGo, and share contact details only when comfortable.</Text></View></ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: 20 }, hero: { flexDirection: 'row', gap: 17, marginTop: 8 }, heroInfo: { flex: 1, paddingTop: 9 }, title: { fontFamily: 'Inter_700Bold', fontSize: 26, lineHeight: 30, marginTop: 13, letterSpacing: -.6 }, meta: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 7 }, cinema: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 14 }, description: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, marginTop: 21, marginBottom: 28 }, times: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, time: { borderRadius: 11, paddingHorizontal: 13, paddingVertical: 11, flexDirection: 'row', gap: 7, alignItems: 'center' }, timeText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, interestNote: { flexDirection: 'row', gap: 8, marginTop: 14, marginBottom: 28 }, note: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 16, flex: 1 }, attendees: { gap: 0 }, person: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 13, borderBottomWidth: 1 }, personName: { fontFamily: 'Inter_600SemiBold', fontSize: 14 }, age: { fontFamily: 'Inter_400Regular', fontSize: 12 }, personMeta: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, safe: { padding: 13, borderRadius: 13, flexDirection: 'row', gap: 9, marginTop: 22 }, safeText: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 16, flex: 1 } });