import React, { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { Avatar } from '@/components/CineGoUI';
import { useColors } from '@/hooks/useColors';
export default function Chat() {
 type Message = { from: 'me' | 'them'; text: string };
 const { id } = useLocalSearchParams<{ id: string }>(); const colors = useColors(); const insets = useSafeAreaInsets(); const [draft, setDraft] = useState(''); const [messages, setMessages] = useState<Message[]>([{ from: 'them', text: 'Hey! I’m also keen for The Last Signal tonight.' }, { from: 'them', text: 'Would 6:45 PM at VOX MOE work for you?' }]);
 const send = () => { if (!draft.trim()) return; setMessages([...messages, { from: 'me', text: draft.trim() }]); setDraft(''); };
 return <View style={[styles.screen, { backgroundColor: colors.background }]}><View style={[styles.person, { borderBottomColor: colors.border }]}><Avatar name={id?.split('-')[1] ?? 'Rohan'} color={colors.accent} /><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{id?.split('-')[1] ?? 'Rohan Arora'}</Text><Text style={[styles.status, { color: colors.primary }]}>Interested in The Last Signal</Text></View><Feather name="more-horizontal" size={20} color={colors.mutedForeground} /></View><FlatList data={messages} keyExtractor={(_, index) => String(index)} contentContainerStyle={styles.messages} renderItem={({ item }) => <View style={[styles.bubble, item.from === 'me' ? { backgroundColor: colors.primary, alignSelf: 'flex-end' } : { backgroundColor: colors.secondary, alignSelf: 'flex-start' }]}><Text style={[styles.bubbleText, { color: item.from === 'me' ? colors.primaryForeground : colors.foreground }]}>{item.text}</Text></View>} /><View style={[styles.footer, { paddingBottom: insets.bottom + 10, borderTopColor: colors.border, backgroundColor: colors.background }]}><TextInput value={draft} onChangeText={setDraft} placeholder="Write a message..." placeholderTextColor={colors.mutedForeground} style={[styles.input, { backgroundColor: colors.secondary, color: colors.foreground }]} onSubmitEditing={send} returnKeyType="send" /><Pressable onPress={send} style={[styles.send, { backgroundColor: colors.primary }]}><Feather name="arrow-up" size={19} color={colors.primaryForeground} /></Pressable></View></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, person: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 16, borderBottomWidth: 1 }, name: { fontFamily: 'Inter_700Bold', fontSize: 15 }, status: { fontFamily: 'Inter_500Medium', fontSize: 11, marginTop: 4 }, messages: { padding: 18, gap: 10, flexGrow: 1, justifyContent: 'flex-end' }, bubble: { borderRadius: 16, padding: 12, maxWidth: '82%' }, bubbleText: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 20 }, footer: { paddingHorizontal: 15, paddingTop: 12, borderTopWidth: 1, flexDirection: 'row', gap: 9, alignItems: 'center' }, input: { borderRadius: 14, minHeight: 46, paddingHorizontal: 15, flex: 1, fontFamily: 'Inter_400Regular', fontSize: 14 }, send: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' } });