import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { MoviePoster, Pill, SectionTitle } from '@/components/CineGoUI';
import { movies } from '@/data/movies';
import { useColors } from '@/hooks/useColors';
import { router } from 'expo-router';
export default function Discover() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const [genre, setGenre] = useState('All films');
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.container, { paddingTop: insets.top + 14, paddingBottom: 118 }]}><View style={styles.head}><Text style={[styles.title, { color: colors.foreground }]}>Discover</Text><Pressable style={[styles.search, { backgroundColor: colors.secondary }]}><Feather name="search" size={18} color={colors.foreground} /></Pressable></View><Text style={[styles.sub, { color: colors.mutedForeground }]}>Films worth leaving the house for.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{['All films', 'Mystery', 'Drama', 'Comedy', 'Action'].map(item => <Pressable key={item} onPress={() => setGenre(item)}><Pill active={genre === item}>{item}</Pill></Pressable>)}</ScrollView><SectionTitle title="Now showing near you" /><View style={styles.list}>{movies.map(movie => <Pressable key={movie.id} onPress={() => router.push(`/movie/${movie.id}`)} style={[styles.row, { borderBottomColor: colors.border }]}><MoviePoster source={movie.poster} small /><View style={styles.info}><Text style={[styles.movieTitle, { color: colors.foreground }]}>{movie.title}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{movie.genre}  ·  {movie.runtime}</Text><View style={styles.cinema}><Feather name="map-pin" size={13} color={colors.primary} /><Text style={[styles.meta, { color: colors.mutedForeground }]}>{movie.cinema} · {movie.area}</Text></View><View style={styles.times}>{movie.times.map(time => <View key={time} style={[styles.time, { backgroundColor: colors.secondary }]}><Text style={[styles.timeText, { color: colors.foreground }]}>{time}</Text></View>)}</View></View><Feather name="chevron-right" size={18} color={colors.mutedForeground} /></Pressable>)}</View></ScrollView>;
}
const styles = StyleSheet.create({ container: { paddingHorizontal: 20 }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, letterSpacing: -.8 }, sub: { fontFamily: 'Inter_400Regular', fontSize: 15, marginTop: 7, marginBottom: 25 }, search: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, filters: { gap: 8, paddingBottom: 30 }, list: { gap: 18 }, row: { flexDirection: 'row', paddingBottom: 18, borderBottomWidth: 1, gap: 13, alignItems: 'center' }, info: { flex: 1 }, movieTitle: { fontFamily: 'Inter_700Bold', fontSize: 16 }, meta: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 5 }, cinema: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 4 }, times: { flexDirection: 'row', gap: 6, marginTop: 10, flexWrap: 'wrap' }, time: { borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, timeText: { fontFamily: 'Inter_600SemiBold', fontSize: 10 } });