import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { Avatar, MoviePoster, PrimaryButton, SectionTitle } from '@/components/CineGoUI';
import { movies } from '@/data/movies';
import { useCineGo } from '@/context/CineGoContext';
import { useColors } from '@/hooks/useColors';
import { router } from 'expo-router';
export default function Plans() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { plans } = useCineGo(); const movie = movies[0];
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.container, { paddingTop: insets.top + 14, paddingBottom: 118 }]}><Text style={[styles.title, { color: colors.foreground }]}>Plans</Text><Text style={[styles.sub, { color: colors.mutedForeground }]}>Your movie nights, all in one place.</Text><View style={[styles.feature, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.featureHead}><MoviePoster source={movie.poster} small /><View style={{ flex: 1 }}><Text style={[styles.label, { color: colors.primary }]}>UPCOMING</Text><Text style={[styles.movie, { color: colors.foreground }]}>{movie.title}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>Today · 6:45 PM · VOX MOE</Text></View><Feather name="more-horizontal" size={20} color={colors.mutedForeground} /></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View style={styles.attendRow}><View style={styles.avatarStack}><Avatar name="You" /><Avatar name="Rohan" color={colors.primary} /><Avatar name="Anjali" color={colors.accent} /></View><Text style={[styles.attendText, { color: colors.mutedForeground }]}><Text style={{ color: colors.foreground, fontFamily: 'Inter_700Bold' }}>4 people</Text> are interested</Text><Pressable onPress={() => router.push('/movie/last-signal')}><Feather name="arrow-up-right" size={18} color={colors.primary} /></Pressable></View></View><SectionTitle title="Requests & chats" /><View style={styles.requests}>{plans.length === 0 ? <View style={[styles.empty, { borderColor: colors.border }]}><Feather name="message-circle" size={26} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No active chats yet</Text><Text style={[styles.emptyText, { color: colors.mutedForeground }]}>When you make a plan with someone, it will show up here.</Text><PrimaryButton label="Find people to go with" icon="users" onPress={() => router.push('/movie/last-signal')} compact /></View> : plans.map(plan => <Pressable key={plan.id} onPress={() => router.push(`/chat/${plan.id}`)} style={[styles.request, { backgroundColor: colors.card, borderColor: colors.border }]}><Avatar name={plan.person} color={colors.accent} /><View style={{ flex: 1 }}><Text style={[styles.requestName, { color: colors.foreground }]}>{plan.person}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{plan.movieId === 'last-signal' ? 'The Last Signal' : 'Movie plan'} · {plan.time}</Text></View><Text style={[styles.pending, { color: colors.accent }]}>{plan.status}</Text><Feather name="chevron-right" size={16} color={colors.mutedForeground} /></Pressable>)}</View></ScrollView>;
}
const styles = StyleSheet.create({ container: { paddingHorizontal: 20 }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, letterSpacing: -.8 }, sub: { fontFamily: 'Inter_400Regular', fontSize: 15, marginTop: 7, marginBottom: 28 }, feature: { borderWidth: 1, borderRadius: 18, padding: 14, marginBottom: 30 }, featureHead: { flexDirection: 'row', gap: 13, alignItems: 'center' }, label: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.1 }, movie: { fontFamily: 'Inter_700Bold', fontSize: 17, marginTop: 6 }, meta: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 5 }, divider: { height: 1, marginVertical: 15 }, attendRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, avatarStack: { flexDirection: 'row' }, attendText: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 12 }, requests: { gap: 10 }, request: { borderWidth: 1, borderRadius: 15, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, requestName: { fontFamily: 'Inter_700Bold', fontSize: 14 }, pending: { fontFamily: 'Inter_600SemiBold', fontSize: 11 }, empty: { borderWidth: 1, borderStyle: 'dashed', borderRadius: 18, padding: 25, alignItems: 'center', gap: 9 }, emptyTitle: { fontFamily: 'Inter_700Bold', fontSize: 16 }, emptyText: { fontFamily: 'Inter_400Regular', fontSize: 12, textAlign: 'center', lineHeight: 18, marginBottom: 8 } });