import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { Avatar, Logo, Pill } from '@/components/CineGoUI';
import { useColors } from '@/hooks/useColors';
export default function Profile() {
 const colors = useColors(); const insets = useSafeAreaInsets();
 return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.container, { paddingTop: insets.top + 14, paddingBottom: 118 }]}><View style={styles.top}><Logo compact /><Pressable style={[styles.settings, { backgroundColor: colors.secondary }]}><Feather name="settings" size={18} color={colors.foreground} /></Pressable></View><View style={styles.profile}><Avatar name="Dhwanit Soni" color={colors.accent} /><Text style={[styles.name, { color: colors.foreground }]}>Dhwanit Soni</Text><Text style={[styles.handle, { color: colors.mutedForeground }]}>Dubai · 4 movies watched with CineGo</Text></View><View style={[styles.stats, { backgroundColor: colors.card, borderColor: colors.border }]}><View><Text style={[styles.statNum, { color: colors.foreground }]}>12</Text><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>Plans made</Text></View><View><Text style={[styles.statNum, { color: colors.foreground }]}>8</Text><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>New friends</Text></View><View><Text style={[styles.statNum, { color: colors.foreground }]}>4</Text><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>Genres</Text></View></View><Text style={[styles.section, { color: colors.foreground }]}>Favourite genres</Text><View style={styles.pills}><Pill active>Mystery</Pill><Pill active>Indie</Pill><Pill>Thriller</Pill><Pill>Drama</Pill></View><Text style={[styles.section, { color: colors.foreground, marginTop: 30 }]}>Preferences</Text>{['Edit profile', 'Location settings', 'Safety & privacy', 'Help centre'].map((item, index) => <Pressable key={item} style={[styles.settingRow, { borderBottomColor: colors.border }]}><View style={[styles.settingIcon, { backgroundColor: colors.secondary }]}><Feather name={['user', 'map-pin', 'shield', 'help-circle'][index] as keyof typeof Feather.glyphMap} size={16} color={colors.primary} /></View><Text style={[styles.settingText, { color: colors.foreground }]}>{item}</Text><Feather name="chevron-right" size={17} color={colors.mutedForeground} /></Pressable>)}</ScrollView>
}
const styles = StyleSheet.create({ container: { paddingHorizontal: 20 }, top: { flexDirection: 'row', justifyContent: 'space-between' }, settings: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, profile: { alignItems: 'center', marginTop: 32 }, name: { fontFamily: 'Inter_700Bold', fontSize: 22, marginTop: 13 }, handle: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 5 }, stats: { borderWidth: 1, borderRadius: 17, flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 17, marginTop: 26 }, statNum: { fontFamily: 'Inter_700Bold', fontSize: 21, textAlign: 'center' }, statLabel: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, section: { fontFamily: 'Inter_700Bold', fontSize: 18, marginBottom: 13 }, pills: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' }, settingRow: { borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', paddingVertical: 13, gap: 12 }, settingIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, settingText: { fontFamily: 'Inter_500Medium', fontSize: 14, flex: 1 } });